import { useEffect, useState } from "react";
import { useLoaderData, useLocation, useNavigate, useParams } from "react-router";
import { addPatient, getAllPatientsAPI, updatePatientsById } from "../business_logic/crud";

export function PatientForm(){
    let {id} = useParams();
    let navigate = useNavigate();
    let location = useLocation();
    let patientDataLoader = useLoaderData();
       
    let resetPatient = {
        id:'',
        patientName:"",
        gender:"",
        date_of_birth:"",
        age:"",
        contact_number:"",
        address:""
    }
    function initialState(){
        if(location.pathname.includes('edit_patients'))
            return patientDataLoader
        else
        
            return resetPatient
    }
    let [patient, setPatient]=useState(()=>initialState());

    function clearForm() {
        setPatient(resetPatient)
        
    }
    function getDetails(ev){
        
        console.log(ev.target.value);
        console.log(ev.target.name);
        setPatient({...patient, [ev.target.name]:ev.target.value}); // copy, key value replace
      
    }
    /* useEffect : to manage lifecycle of functional component
    1. intially useEffect gets called when componets gets mounted
    ( note : in development mode components gets mounted 2 times)
    2. after that useEffect hook gets called everytime when UI gets updated due to state change in variable */
    useEffect(()=>{
        /* later we will pass this object to the backend */
        console.log(patient); 
        console.log(location);
        console.log('patientDataLoader-',patientDataLoader);
        
        
    });

    async function handlePatientSubmit(eve){
        eve.preventDefault();
        if(patient.id){
            const update_data = await updatePatientsById(patient.id, patient)
            if (update_data!=null) {
                alert(`Patient ${update_data.id} updated successfully !`)
                navigate('/list_patients')
            }
        }
        else{
            const add_data = await addPatient(patient);
            if (add_data!=null) {
                alert(`Patient with ${add_data.id} added successfully !`)
                navigate('/list_patients')
            }
        
        }        
        }

    return(
        <div className="border border-5 border-info bg-dark text-white" style={{margin:'5px 100px'}}>
        <h4 className="text-center">Patient Form</h4>
        <form className="m-5" onSubmit={handlePatientSubmit}>
        <div className="mb-3">
                <label htmlFor="id" className="form-label">PatientId</label>
                <input type="text" className="form-control" value={patient.id} placeholder="Id is autogenerated"
                onChange={getDetails} id="id" name="id" readOnly />
            </div>
            <div className="mb-3">
                <label htmlFor="patientName" className="form-label">Patient Name</label>
                <input type="text" className="form-control" value={patient.patientName} 
                onChange={getDetails} id="patientName" name="patientName"/>
            </div>
            <div className="mb-3">
                <label htmlFor="gender" className="form-label">Gender</label>
                <input type="text" className="form-control" id="gender" name="gender" value={patient.gender} 
                onChange={getDetails}  />
            </div>
            <div className="mb-3">
                <label htmlFor="date_of_birth" className="form-label">Date Of Birth</label>
                <input type="datetime-local" className="form-control" id="date_of_birth"  name="date_of_birth"
                value={patient.date_of_birth} onChange={getDetails}  />
            </div>
            <div className="mb-3">
                <label htmlFor="age" className="form-label">Age</label>
                <input type="number" className="form-control" id="age"  name="age"
                value={patient.age} onChange={getDetails}  />
                
            </div>
            <div className="mb-3">
                <label htmlFor="contact_number" className="form-label">Contact Number</label>
                <input type="number" className="form-control" id="contact_number"  name="contact_number"
                value={patient.contact_number} onChange={getDetails}  />
                
            </div>
            <div className="mb-3">
                <label htmlFor="address" className="form-label">Address</label>
                <input type="text" className="form-control" id="address" name="address" value={patient.address} 
                onChange={getDetails}  />
            </div>



            <div style={{ display: "flex", gap: "10px" }}>
                <button type="submit" className="btn btn-primary">{location.pathname.includes('edit_patients') ? 'Update':'Add'}</button>
                <button type="reset" onClick={clearForm} className="btn btn-primary">Reset</button>
            </div>
        </form>
        </div>
      
    );
}